title: Operação Cavalcante 2021
description: > # this means to ignore newlines until "show_excerpts:"
  A Operação Cavalcante é uma iniciativa de voluntariado que pretende
  levar água encanada, saúde e maior dignidade a um dos municípios
  mais vulneráveis do estado de Goiás.
url: https://cavalcante.pages.dev/ # change this URL, this is needed for generating right sitemap

permalink: "/blog/:title/"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-purgecss
  - jekyll-sitemap
  - jekyll-minifier

css_dir: "assets/css" # defaults to "css"

highlighter: rouge

collections:
  posts:
    output: true
    permalink: "/blog/:title"
  pages:
    output: true
    permalink: "/:title"

jekyll-minifier:
  uglifier_args:
    harmony: true

soopr:
  publish_token: "" # sign up at https://www.soopr.co to get your publish token and personalize share and reaction options

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - postcss.config.js
  - purgecss.config.js
  - tailwind.config.js
  - .gitignore
  - vendor
